# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Just dash of opacity by default
windowrule = match:class .*, opacity 0.97 0.9

# App-specific tweaks
source = ~/.local/share/archbrigade/default/hypr/apps.conf
