# All the default ArchBrigade aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/archbrigade/default/zsh/rc

# Add your own exports, aliases, and functions here.
#
# alias p='python'
