echo "Convert Hyprland configuration from .conf to Lua"

ARCHBRIGADE_PATH="${ARCHBRIGADE_PATH:-$HOME/.local/share/archbrigade}"
HYPR_DIR="$HOME/.config/hypr"
TEMPLATE_DIR="$ARCHBRIGADE_PATH/config/hypr"

mkdir -p "$HYPR_DIR"

# 1. Back up the user's legacy Hyprland .conf files. hypridle/hyprlock/
#    hyprsunset stay .conf and keep working; monitors.conf stays in place as
#    the nwg-displays source for archbrigade-sync-monitors.
backed_up=()
for conf in "$HYPR_DIR"/*.conf; do
  [[ -f $conf ]] || continue
  case "$(basename "$conf")" in
    hypridle.conf | hyprlock.conf | hyprsunset.conf | monitors.conf) continue ;;
  esac
  if [[ ! -e "$conf.pre-lua.bak" ]]; then
    mv "$conf" "$conf.pre-lua.bak"
    backed_up+=("$conf.pre-lua.bak")
  fi
done

# 2. Install the Lua config templates, but only when missing so a re-run
#    never clobbers files the user has since edited.
for file in .luarc.json hyprland.lua autostart.lua bindings.lua envs.lua input.lua looknfeel.lua monitors.lua; do
  if [[ ! -f "$HYPR_DIR/$file" ]]; then
    cp "$TEMPLATE_DIR/$file" "$HYPR_DIR/$file"
  fi
done

# 3. Seed the toggle flags state that default/hypr/toggles.lua loads.
mkdir -p "$HOME/.local/state/archbrigade/toggles/hypr"
if [[ ! -f "$HOME/.local/state/archbrigade/toggles/hypr/flags.lua" ]]; then
  cp "$ARCHBRIGADE_PATH/default/hypr/toggles/flags.lua" "$HOME/.local/state/archbrigade/toggles/hypr/"
fi

# 4. Convert an existing nwg-displays monitors.conf into monitors.lua, unless
#    the user has already customized monitors.lua by hand.
if [[ -f "$HYPR_DIR/monitors.conf" ]]; then
  if [[ ! -f "$HYPR_DIR/monitors.lua" ]] ||
    grep -q "generated by archbrigade-sync-monitors" "$HYPR_DIR/monitors.lua" ||
    cmp -s "$HYPR_DIR/monitors.lua" "$TEMPLATE_DIR/monitors.lua"; then
    "$ARCHBRIGADE_PATH/bin/archbrigade-sync-monitors" || true
  fi
fi

# 5. Warn when the current theme predates the Lua conversion. Its Hyprland
#    overrides are skipped (everything else still applies) until it ships a
#    hyprland.lua.
CURRENT_THEME="$HOME/.config/archbrigade/current/theme"
if [[ -f "$CURRENT_THEME/hyprland.conf" && ! -f "$CURRENT_THEME/hyprland.lua" ]]; then
  echo "Warning: your current theme only ships hyprland.conf (pre-Lua). Its Hyprland overrides will be skipped until the theme provides hyprland.lua."
fi

# 6. Reload Hyprland only when it is running and this build supports the Lua
#    config (the hl stubs ship with Lua-capable Hyprland). Tolerate failure.
if command -v hyprctl &>/dev/null && pgrep -x Hyprland &>/dev/null && [[ -f /usr/share/hypr/stubs/hl.meta.lua ]]; then
  hyprctl reload &>/dev/null || true
fi

# 7. Tell the user what moved. Custom .conf tweaks are deliberately NOT
#    auto-translated; the backups are the contract.
if ((${#backed_up[@]} > 0)); then
  echo
  echo "Hyprland now uses Lua configs (~/.config/hypr/*.lua)."
  echo "Your previous .conf files were backed up as:"
  printf '  %s\n' "${backed_up[@]}"
  echo "Custom settings in those files were NOT auto-translated."
  echo "Re-add them to the matching ~/.config/hypr/*.lua files."
fi
