# Fixing popup size issue
windowrule = match:class (.*jetbrains.*)$, title:^$,floating:1, size 50% 50%

# Fix tab dragging (always have a single space character as their title)
windowrule = match:class ^(.*jetbrains.*)$, title:^\\s$, noinitialfocus
windowrule = match:class ^(.*jetbrains.*)$, title:^\\s$, nofocus
