# Float Steam
windowrule = match:class steam, float on
windowrule = match:class steam, title:Steam, center on
windowrule = match:class steam, opacity 1 1
windowrule = match:class steam, title:Steam, size 1100 700
windowrule = match:class steam, title:Friends List, size 460 800
windowrule = match:class steam, idleinhibit fullscreen
