run_logged $ARCHBRIGADE_INSTALL/config/cleanup-old-configs.sh
run_logged $ARCHBRIGADE_INSTALL/config/config.sh
run_logged $ARCHBRIGADE_INSTALL/config/ohmyzsh.sh
run_logged $ARCHBRIGADE_INSTALL/config/elephant.sh
run_logged $ARCHBRIGADE_INSTALL/config/theme.sh
run_logged $ARCHBRIGADE_INSTALL/config/branding.sh
run_logged $ARCHBRIGADE_INSTALL/config/git.sh
run_logged $ARCHBRIGADE_INSTALL/config/gpg.sh
run_logged $ARCHBRIGADE_INSTALL/config/timezones.sh
run_logged $ARCHBRIGADE_INSTALL/config/increase-sudo-tries.sh
run_logged $ARCHBRIGADE_INSTALL/config/increase-lockout-limit.sh
run_logged $ARCHBRIGADE_INSTALL/config/ssh-flakiness.sh
run_logged $ARCHBRIGADE_INSTALL/config/xcompose.sh
run_logged $ARCHBRIGADE_INSTALL/config/mise-work.sh
run_logged $ARCHBRIGADE_INSTALL/config/fix-powerprofilesctl-shebang.sh
run_logged $ARCHBRIGADE_INSTALL/config/docker.sh
run_logged $ARCHBRIGADE_INSTALL/config/mimetypes.sh
run_logged $ARCHBRIGADE_INSTALL/config/localdb.sh
run_logged $ARCHBRIGADE_INSTALL/config/claude.sh
run_logged $ARCHBRIGADE_INSTALL/config/sudoless-asdcontrol.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/network.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/set-wireless-regdom.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/fix-fkeys.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/bluetooth.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/printer.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/usb-autosuspend.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/ignore-power-button.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/nvidia.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/gpu.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/cpu-microcode.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/intel.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/fix-f13-amd-audio-input.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/fix-apple-bcm43xx.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/fix-apple-spi-keyboard.sh
run_logged $ARCHBRIGADE_INSTALL/config/hardware/fix-apple-t2.sh
