# Preserve user's monitors.conf if it exists (auto-generated by nwg-displays)
MONITORS_BAK=""
if [[ -f ~/.config/hypr/monitors.conf ]]; then
  MONITORS_BAK=$(cat ~/.config/hypr/monitors.conf)
fi

# Copy over ArchBrigade configs
mkdir -p ~/.config
cp -R ~/.local/share/archbrigade/config/* ~/.config/

# Restore monitors.conf — never overwrite user's monitor layout
if [[ -n "$MONITORS_BAK" ]]; then
  echo "$MONITORS_BAK" > ~/.config/hypr/monitors.conf
fi

# Quickshell overview config
mkdir -p ~/.config/quickshell
cp -R ~/.local/share/archbrigade/config/quickshell/* ~/.config/quickshell/

# Walker config needs actual home path (doesn't expand ~ or $HOME)
sed -i "s|\$HOME|$HOME|g" ~/.config/walker/config.toml

# Use default bashrc from ArchBrigade
cp ~/.local/share/archbrigade/default/bashrc ~/.bashrc

# Use default zshrc from ArchBrigade and set zsh as default shell
if [[ -f ~/.zshrc ]]; then
  ZSHRC_BAK=~/.zshrc.pre-archbrigade-$(date +%Y%m%d-%H%M%S)
  cp ~/.zshrc "$ZSHRC_BAK"
  echo ""
  echo "╔══════════════════════════════════════════════════════╗"
  echo "║  Your existing .zshrc has been backed up to:        ║"
  echo "║  $ZSHRC_BAK"
  echo "║  Your aliases, exports and customizations are safe. ║"
  echo "╚══════════════════════════════════════════════════════╝"
  echo ""
fi
cp ~/.local/share/archbrigade/default/zshrc ~/.zshrc
sudo usermod -s /bin/zsh "$USER"
