# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults ArchBrigade defaults (but don't edit these directly!)
source = ~/.local/share/archbrigade/default/hypr/autostart.conf
source = ~/.local/share/archbrigade/default/hypr/bindings/media.conf
source = ~/.local/share/archbrigade/default/hypr/bindings/tiling.conf
source = ~/.local/share/archbrigade/default/hypr/bindings/clipboard.conf
source = ~/.local/share/archbrigade/default/hypr/bindings/utilities.conf
source = ~/.local/share/archbrigade/default/hypr/envs.conf
source = ~/.local/share/archbrigade/default/hypr/looknfeel.conf
source = ~/.local/share/archbrigade/default/hypr/input.conf
source = ~/.local/share/archbrigade/default/hypr/windows.conf
source = ~/.config/archbrigade/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

plugin {
    hyprexpo {
        columns = 3
        gap_size = 10
        bg_col = rgb(111111)
    }
}
